//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FtpDescuentoSocios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentoSocio
    {
        public int IdDescuentoSocio { get; set; }
        public Nullable<int> IdSocio { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdUsrCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsrUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Socio Socio { get; set; }
        public virtual Cliente SRV_Clientes { get; set; }
    }
}
