//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FtpDescuentoSocios.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eFarmaxEntities : DbContext
    {
        public eFarmaxEntities()
            : base("name=eFarmaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DescuentoSocio> DescuentoSocios { get; set; }
        public DbSet<Socio> Socios { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
    }
}
